name: Android Release Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  build:
    name: Build Signed Release APK & AAB
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Create .env File
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Decode Release Keystore
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 --decode > my-upload-key.jks

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Release APK and AAB
        run: ./gradlew assembleRelease bundleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v6
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk

      - name: Upload Release AAB (App Bundle)
        uses: actions/upload-artifact@v6
        with:
          name: release-aab
          path: app/build/outputs/bundle/release/app-release.aab
